In [3]:
# ndarray
# https://wikidocs.net/14606
import numpy as np

x = np.array((0.1,0.2,0.3))    # np.array([0.1,0.2,0.3])도 가능

print(x)
print(x.shape)
print(x.dtype)

y = np.array(((1,2,3),(4,5,6)))    # [(1,2,3),(4,5,6)],[[1,2,3],[4,5,6]] 등도 가능

print(y)
print(y.dtype)
print(y.shape)

z = np.array([1,2,3],dtype='float64')

print(z)
print(z.dtype)
print(z.shape)

[0.1 0.2 0.3]
(3,)
float64
[[1 2 3]
 [4 5 6]]
int64
(2, 3)
[1. 2. 3.]
float64
(3,)


In [4]:
X = np.zeros((3,3))
print(X)

Y = np.ones((3,3),dtype='int32')
print(Y)

Z = np.empty((3,3))
print(Z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
import numpy as np

A = np.array([])
for i in range(3):
    A = np.append(A,[1,2,3])

print(A)

[1. 2. 3. 1. 2. 3. 1. 2. 3.]


In [6]:
print(np.arange(1,2,0.1))
print(np.arange(10))   # start, step 생략가능. 정수로 생성)
print(np.arange(10.))  # start, step 생략가능. 실수로 생성)
print(np.linspace(0.,20.,11))
print(np.eye(3))

[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9]
[0 1 2 3 4 5 6 7 8 9]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18. 20.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
X = np.arange(0,9,1.)
print(X)

Y = np.reshape(X,(3,3))
Z = X.reshape((3,3))
print(Y)
print(Z)

X.shape = (3,3)
print(X)

[0. 1. 2. 3. 4. 5. 6. 7. 8.]
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


In [13]:
a = np.arange(3);
a = a.astype(int)
a = a.astype('int32')
print(a.dtype)
a = a.astype('int64')
print(a.dtype)

a = a.astype(float)    # a.astype('float64')
a = a.astype('float32')
print(a.dtype)
a = a.astype('float64')
print(a.dtype)

int32
int64
float32
float64
