In [3]:
# Indexing
# https://wikidocs.net/14607
import numpy as np

a = np.array([1.2,-1.3,2.2,5.3,3.7])

print(a)
print(a[0])
print(a[0:3])
print(a[-1])
print(a[-2])
print(a[0:-1])

a = np.array([1.2,-1.3,2.2,5.3,3.7])
idx = [0,3]
print(a[idx])

[ 1.2 -1.3  2.2  5.3  3.7]
1.2
[ 1.2 -1.3  2.2]
3.7
5.3
[ 1.2 -1.3  2.2  5.3]
[1.2 5.3]


In [4]:
x = np.array([1.2, -1.3, 0., 2.2, 0., 5.3, 3.7])
print(x > 2)

idx = x>2
print(idx)
print(x[idx])

x = np.array([1.2, -1.3, 0., 2.2, 0., 5.3, 3.7])
print(x[x > 2])

x = np.array([1.2, -1.3, 0., 2.2, 0., 5.3, 3.7])
print(np.nonzero(x))

x = np.array([1.2, -1.3, 0., 2.2, 0., 5.3, 3.7])
print(np.nonzero(x>2))

[False False False  True False  True  True]
[False False False  True False  True  True]
[2.2 5.3 3.7]
[2.2 5.3 3.7]
(array([0, 1, 3, 5, 6]),)
(array([3, 5, 6]),)


In [5]:
# Concatenate

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
print(np.concatenate((a, b), axis=0))

print(np.concatenate((a, b.T), axis=1))

[[1 2]
 [3 4]
 [5 6]]
[[1 2 5]
 [3 4 6]]


In [6]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a)
print(b)
print(np.vstack((a,b)))
print(np.hstack((a,b)))

c = np.append(a,b)
print(c)


[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[1 2 3 4 5 6]
