In [1]:
# https://wikidocs.net/14597

import numpy as np

a = np.array([1,2,3,4])
b = np.array([4,5,6,7])

# 기본적으로 element-wise 연산d
# 요소가 아닌 배열에 대해 연산 적용 -> vectorization
print(a+b)
print(a*b)
print(a**2)
print(a+2)   # 상수 2는 같은 크기의 배열로 인식
print(10*np.sin(a))    # NumPy의 universal 함수 sin() 적용
print(a<3)
a *= b    # a = a*b와 동일
print(a)


[ 5  7  9 11]
[ 4 10 18 28]
[ 1  4  9 16]
[3 4 5 6]
[ 8.41470985  9.09297427  1.41120008 -7.56802495]
[ True  True False False]
[ 4 10 18 28]


In [7]:
x = np.arange(3)                      # (3,)
y = np.arange(3).reshape(3,1)         # (3,1)
z = np.arange(3).reshape(1,3)         # (1,3)

print(x)
print(y)
print(z)

[0 1 2]
[[0]
 [1]
 [2]]
[[0 1 2]]


In [9]:
A = np.arange(9).reshape(3,3)         # (3,3)
B = np.arange(11,11+9).reshape(3,3)   # (3,3)

print(A)
print(B)

#  C = A*B  ... same results
C1 = np.dot(A,B) # 내적
C2 = np.matmul(A,B) # 행렬곱
C3 = A@B # 행렬곱

print(C1)
print(C2)
print(C3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 48  51  54]
 [174 186 198]
 [300 321 342]]
[[ 48  51  54]
 [174 186 198]
 [300 321 342]]
[[ 48  51  54]
 [174 186 198]
 [300 321 342]]


In [10]:
# A*x ... 2d*1d  ... same results
Ax1 = np.dot(A,x) # array([ 5, 14, 23])
Ax2 = np.matmul(A,x)
Ax3 = A@x

print(Ax1)
print(Ax2)
print(Ax3)

[ 5 14 23]
[ 5 14 23]
[ 5 14 23]


In [ ]:
# A*y ... 2d*(2d,but 1d vector) ... same results
Ay1 = np.dot(A,x)     # array([[ 5],[14],[23]])
Ay2 = np.matmul(A,x)
Ay3 = A@y

print(Ay1)
print(Ay2)
print(Ay3)

In [ ]:
# A*z ... 2d*(2d, but 1d vector)  ... all dimension error
Az1 = np.dot(A,z.T)     # array([[ 5],[14],[23]])
Az2 = np.matmul(A,z.T)
Az3 = A@z.T


# left make (row vector), right make (column vector)
xy = x@y   # array([5])

print(Az1)
print(Az2)
print(Az3)
print(xy)