In [2]:
import numpy as np

A = np.arange(9.).reshape(3,3)   # 2d array : (3,3)
x = np.array([1.,0,0])   # 1d array : (3,)
y = x.reshape(1,3)       # 2d array : (1,3)
z = x.reshape(3,1)       # 2d array : (3,1)

print(A)
print(x)
print(y)
print(z)

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
[1. 0. 0.]
[[1. 0. 0.]]
[[1.]
 [0.]
 [0.]]


In [6]:
print(A + 1)
print(A + x)
print(A + y)
print(A + z)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[1. 1. 2.]
 [4. 4. 5.]
 [7. 7. 8.]]
[[1. 1. 2.]
 [4. 4. 5.]
 [7. 7. 8.]]
[[1. 2. 3.]
 [3. 4. 5.]
 [6. 7. 8.]]
