In [1]:
import numpy as np
a = [1,2,3]
x = np.array(a)
y = x     # shallow copy
y[0]=10

print(a)
print(x)
print(y)
print(x is y)

z = x.copy()   # deep copy
print(z is x)

[1, 2, 3]
[10  2  3]
[10  2  3]
True
False


In [4]:
x = np.array([1,2,3])
y = x[0:3] # list slicing is deep copy
y[0] = 10

print(x)
print(y)
print(x is y)

[10  2  3]
[10  2  3]
False
