In [2]:
import numpy as np

x = np.arange(9).reshape(3,3)
np.savetxt('3by3.txt',x)
y = np.loadtxt('3by3.txt')

print(x)
print(y)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


In [3]:
x1 = np.array([1.1,2.2,3.1])
np.savetxt('x1.txt',x1)

x2 = np.array([1.1,2.2,3.1]).reshape(1,3)
np.savetxt('x2.txt',x2)

x3 = np.array([1.1,2.2,3.1]).reshape(3,1)
np.savetxt('x3.txt',x3)

y1 = np.loadtxt('x1.txt')  # array([1.1, 2.2, 3.1])
y2 = np.loadtxt('x1.txt')  # array([1.1, 2.2, 3.1])
y3 = np.loadtxt('x1.txt')  # array([1.1, 2.2, 3.1])

print(x1)
print(y1)
print(x2)
print(y2)
print(x3)
print(y3)

[1.1 2.2 3.1]
[1.1 2.2 3.1]
[[1.1 2.2 3.1]]
[1.1 2.2 3.1]
[[1.1]
 [2.2]
 [3.1]]
[1.1 2.2 3.1]


In [8]:
A = np.array([1,2,3,4,5,6,7,8,9])
A.tofile('backup')   # 저장


Anew = np.fromfile('backup', dtype=int)    # 저장했던 값을 A_new로 loading
print(A)
print(Anew)

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [9]:
import numpy as np
acc = np.random.random(1024)  # 1024 points in [0,1.0)
dt = 60.0
station = 3
np.savez('acceleration.npz',acc=acc,dt=dt, station=station)
data = np.load('acceleration.npz')
data["acc"]
print(data["acc"])
print(data["dt"])
print(data["station"])

[0.52007762 0.42007698 0.53478668 ... 0.61080294 0.89437834 0.8984299 ]
60.0
3
